gfx/env/nightsky_bk.tga
gfx/env/nightsky_dn.tga
gfx/env/nightsky_ft.tga
gfx/env/nightsky_lf.tga
gfx/env/nightsky_rt.tga
gfx/env/nightsky_up.tga
models/truckstop/trailer.mdl
models/truckstop/junkytrl.mdl
models/truckstop/largecar1.mdl
sprites/fire2.spr
sound/fire.wav
sound/truckstop/little_ride.wav
models/truckstop/mack2.mdl
models/truckstop/peterbilt.mdl
models/truckstop/kenworth_w_tanker_v3.mdl
models/truckstop/bus.mdl
models/truckstop/kenworth2.mdl
models/truckstop/b4x4.mdl
models/truckstop/car1.mdl
models/truckstop/gmc_norm2.mdl
models/truckstop/truck_old_2.mdl
models/truckstop/fan02.mdl
sound/ambient/machines/power_transformer_loop_2.wav
models/truckstop/phone.mdl
models/truckstop/sg_smcouch.mdl
models/truckstop/plant_potted.mdl
models/truckstop/copcar_v2.mdl
models/truckstop/seif.mdl
models/truckstop/coke_box.mdl
models/truckstop/hostage03.mdl
models/truckstop/hostage01.mdl
models/truckstop/cactus_medium.mdl
sound/flies.wav
sound/wind_se.wav
sound/truckstop/acdc_highway_to_hell.wav
sound/truckstop/iloverockandroll.wav
sound/truckstop/gimmegimmegimme.wav
sound/truckstop/police_chatter.wav
sound/cricket.wav
maps/cs_truckstop.bsp
