gfx/env/downtownbk.tga
gfx/env/downtowndn.tga
gfx/env/downtownft.tga
gfx/env/downtownlf.tga
gfx/env/downtownrt.tga
gfx/env/downtownup.tga
models/townside/antenna_urban.mdl
models/townside/bench.mdl
models/townside/bg_table_set.mdl
models/townside/dt_fan.mdl
models/townside/dt_poolballs.mdl
models/townside/dt_tree.mdl
models/townside/dt_wtower.mdl
models/townside/fan_lamborghini.mdl
models/townside/gins_clock.mdl
models/townside/halla_grass1c.mdl
models/townside/iw_picnic.mdl
models/townside/lv_bottle.mdl
models/townside/phone_pay-US.mdl
models/townside/pi_treeb.mdl
models/townside/trash.mdl
models/townside/trash_02.mdl
sound/townside/Birds9.wav
sound/townside/dt_bells.wav
sound/townside/dt_blues.wav
sound/townside/dt_earlybirdies.wav
sound/townside/dt_fountain.wav
sprites/dt_glow.spr
maps/de_escalation.nav
maps/de_escalation.res
maps/de_escalation.txt
overviews/de_escalation.bmp
overviews/de_escalation.txt
