// .res entries (20):
gfx/env/xzenon_day_bk.tga
gfx/env/xzenon_day_dn.tga
gfx/env/xzenon_day_ft.tga
gfx/env/xzenon_day_lf.tga
gfx/env/xzenon_day_rt.tga
gfx/env/xzenon_day_up.tga
models/de_giza/Camel.mdl
models/de_giza/CamelSit.mdl
models/de_giza/Cobra.mdl
models/de_giza/de_giza_v1.mdl
models/de_giza/Fish.mdl
models/de_giza/Fish_1.mdl
models/de_giza/Gator.mdl
sound/de_giza/Burn.wav
sound/de_giza/Drips.wav
sound/de_giza/Water.wav
sound/de_giza/Wind.wav
sprites/de_giza/Fire.spr
sprites/de_giza/Glow_Sun.spr
sprites/de_giza/Steam.spr
