// Resources file
// © trankschenke.de
// Version: 2020-11 - J.D.Rock

// AmxModX Miscstats Sounds
sound/amxmodx/c4powa.wav
sound/amxmodx/doublekill.wav
sound/amxmodx/firstblood.wav
sound/amxmodx/flatline.wav
sound/amxmodx/godlike.wav
sound/amxmodx/grenade.wav
sound/amxmodx/headshot.wav
sound/amxmodx/humiliation.wav
sound/amxmodx/killingspree.wav
sound/amxmodx/laugh.wav
sound/amxmodx/maytheforce.wav
sound/amxmodx/monsterkill.wav
sound/amxmodx/multikill.wav
sound/amxmodx/oneandonly.wav
sound/amxmodx/prepare.wav
sound/amxmodx/rampage.wav
sound/amxmodx/unstoppable.wav
sound/amxmodx/ultrakill.wav
sound/amxmodx/witch.wav

// AmxModX Parachute
models/parachute.mdl

// AmxModX Adminmodels
models/player/admin_ct/admin_ct.mdl
models/player/admin_te/admin_te.mdl

// AmxModX Chickenmod
models/player/chicken/chicken.mdl
models/w_easterEgg.mdl
models/w_goldenEgg.mdl
sound/misc/chicken0.wav
sound/misc/chicken1.wav
sound/misc/chicken2.wav
sound/misc/chicken3.wav
sound/misc/chicken4.wav
sound/misc/knife_hit1.wav
sound/misc/knife_hit3.wav

// AmxModX Warcraft 3 Frozen Throne
sound/warcraft3/bonus/Error.wav
sound/warcraft3/soundpack/barkskintarget1.wav
sound/warcraft3/soundpack/berzerkercaster.wav
sound/warcraft3/soundpack/entanglingrootsdecay1.wav
sound/warcraft3/soundpack/faeriefirelaunch1.wav
sound/warcraft3/soundpack/frostarmortarget1.wav
sound/warcraft3/soundpack/innerfirebirth.wav
sound/warcraft3/soundpack/reincarnation.wav
sound/warcraft3/soundpack/shadowstrikebirth1.wav
sound/warcraft3/antend.wav
sound/warcraft3/banishcaster.wav
sound/warcraft3/blinkarrival.wav
sound/warcraft3/carrionswarmdamage1.wav
sound/warcraft3/carrionswarmlaunch1.wav
sound/warcraft3/DispelMagicTarget.wav
sound/warcraft3/divineshield.wav
sound/warcraft3/entanglingrootstarget1.wav
sound/warcraft3/error.wav
sound/warcraft3/flamestriketargetwavenonloop1.wav
sound/warcraft3/ImmolationDecay1.wav
sound/warcraft3/impalehit.wav
sound/warcraft3/impalelaunch1.wav
sound/warcraft3/levelupcaster.wav
sound/warcraft3/lightningbolt.wav
sound/warcraft3/locustswarmloop.wav
sound/warcraft3/massteleporttarget.wav
sound/warcraft3/MiniSpiritPissed1.wav
sound/warcraft3/pickupitem.wav
sound/warcraft3/PolymorphDone.wav
sound/warcraft3/PossessionMissileHit1.wav
sound/warcraft3/PossessionMissileLaunch1.wav
sound/warcraft3/PurgeTarget1.wav
sound/warcraft3/resurrecttarget.wav
sound/warcraft3/shadowstrikebirth.wav
sound/warcraft3/shadowstrikemissile1.wav
sound/warcraft3/SpellShieldImpact1.wav
sound/warcraft3/Tomes.wav
sprites/warcraft3/items/wc3_ankh_01.spr
sprites/warcraft3/items/wc3_boot_01.spr
sprites/warcraft3/items/wc3_cat_01.spr
sprites/warcraft3/items/wc3_chameleon_01.spr
sprites/warcraft3/items/wc3_claws_01.spr
sprites/warcraft3/items/wc3_cloak_01.spr
sprites/warcraft3/items/wc3_feather_01.spr
sprites/warcraft3/items/wc3_frost_01.spr
sprites/warcraft3/items/wc3_health_01.spr
sprites/warcraft3/items/wc3_helm_01.spr
sprites/warcraft3/items/wc3_immunity_01.spr
sprites/warcraft3/items/wc3_inferno_01.spr
sprites/warcraft3/items/wc3_mask_01.spr
sprites/warcraft3/items/wc3_mole_01.spr
sprites/warcraft3/items/wc3_protectant_01.spr
sprites/warcraft3/items/wc3_regen_01.spr
sprites/warcraft3/items/wc3_respawn_01.spr
sprites/warcraft3/items/wc3_tome_01.spr
sprites/warcraft3/level/a_level_0.spr
sprites/warcraft3/level/a_level_1.spr
sprites/warcraft3/level/a_level_2.spr
sprites/warcraft3/level/a_level_3.spr
sprites/warcraft3/level/a_level_4.spr
sprites/warcraft3/level/a_level_5.spr
sprites/warcraft3/level/a_level_6.spr
sprites/warcraft3/level/a_level_7.spr
sprites/warcraft3/level/a_level_8.spr
sprites/warcraft3/level/a_level_9.spr
sprites/warcraft3/level/a_level_10.spr
sprites/warcraft3/races/wc3_bloodmage_01.spr
sprites/warcraft3/races/wc3_bloodmage_hi.spr
sprites/warcraft3/races/wc3_chameleon_01.spr
sprites/warcraft3/races/wc3_cryptlord_01.spr
sprites/warcraft3/races/wc3_cryptlord_hi.spr
sprites/warcraft3/races/wc3_elves_01.spr
sprites/warcraft3/races/wc3_elves_hi.spr
sprites/warcraft3/races/wc3_human_01.spr
sprites/warcraft3/races/wc3_human_hi.spr
sprites/warcraft3/races/wc3_none_01.spr
sprites/warcraft3/races/wc3_none_hi.spr
sprites/warcraft3/races/wc3_orc_01.spr
sprites/warcraft3/races/wc3_orc_hi.spr
sprites/warcraft3/races/wc3_shadow_01.spr
sprites/warcraft3/races/wc3_shadow_hi.spr
sprites/warcraft3/races/wc3_undead_01.spr
sprites/warcraft3/races/wc3_undead_hi.spr
sprites/warcraft3/races/wc3_warden_01.spr
sprites/warcraft3/races/wc3_warden_hi.spr
sprites/warcraft3/fireball.spr
sprites/warcraft3/snow.spr
wc3.css

// Map Files
chateau.wad
cs_damage_esc.wad
de_piranesi.wad
gfx/env/greendn.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
gfx/env/greenbk.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
hogwarts1.wad
maps/de_hogwarts.nav
maps/de_hogwarts.bsp
maps/de_hogwarts.txt
maps/de_hogwarts.res
models/hp/singlecandle.mdl
models/hp/jellyblue.mdl
models/hp/potionscauldron.mdl
models/hp/gryfcouchmesh.mdl
models/hp/flipgreenvase.mdl
models/hp/rememberall.mdl
models/hp/skknightmesh.mdl
models/hp/transblackboardmesh.mdl
models/hp/hogtrestlebenchmesh.mdl
models/hp/flipgreenvaseshard.mdl
models/hp/gryftrunk.mdl
models/hp/gryftable.mdl
models/hp/snitch.mdl
models/hp/dresser.mdl
models/hp/fireplacewood.mdl
models/hp/broom.mdl
models/hp/gryfchairmesh.mdl
models/hp/gryfbedmesh.mdl
models/hp/lamppostmesh.mdl
models/hp/telescope.mdl
models/hp/bigbook.mdl
models/hp/gryftrunck2.mdl
models/hp/threecandle.mdl
models/hp/gryfarmoiremesh.mdl
models/hp/DettanyMesh.mdl
models/hp/hunchbackwitch.mdl
models/hp/firewood.mdl
models/hp/skbronzechestMesh.mdl
models/hp/greg.mdl
overviews/de_hogwarts.bmp
overviews/de_hogwarts.txt
sound/hp/falldeep2.wav
sound/hp/hagrid.wav
sound/hp/pick_bean.wav
sound/hp/cave_drips1.wav
sound/hp/vase_breaking.wav
sound/hp/pit.wav
