// Resources file
// © trankschenke.de
// Version: 2020-11 - J.D.Rock

// AmxModX Miscstats Sounds
sound/amxmodx/c4powa.wav
sound/amxmodx/doublekill.wav
sound/amxmodx/firstblood.wav
sound/amxmodx/flatline.wav
sound/amxmodx/godlike.wav
sound/amxmodx/grenade.wav
sound/amxmodx/headshot.wav
sound/amxmodx/humiliation.wav
sound/amxmodx/killingspree.wav
sound/amxmodx/laugh.wav
sound/amxmodx/maytheforce.wav
sound/amxmodx/monsterkill.wav
sound/amxmodx/multikill.wav
sound/amxmodx/oneandonly.wav
sound/amxmodx/prepare.wav
sound/amxmodx/rampage.wav
sound/amxmodx/unstoppable.wav
sound/amxmodx/ultrakill.wav
sound/amxmodx/witch.wav

// AmxModX Parachute
models/parachute.mdl

// AmxModX Adminmodels
models/player/admin_ct/admin_ct.mdl
models/player/admin_te/admin_te.mdl

// AmxModX Chickenmod
models/player/chicken/chicken.mdl
models/w_easterEgg.mdl
models/w_goldenEgg.mdl
sound/misc/chicken0.wav
sound/misc/chicken1.wav
sound/misc/chicken2.wav
sound/misc/chicken3.wav
sound/misc/chicken4.wav
sound/misc/knife_hit1.wav
sound/misc/knife_hit3.wav

// AmxModX Warcraft 3 Frozen Throne
sound/warcraft3/bonus/Error.wav
sound/warcraft3/soundpack/barkskintarget1.wav
sound/warcraft3/soundpack/berzerkercaster.wav
sound/warcraft3/soundpack/entanglingrootsdecay1.wav
sound/warcraft3/soundpack/faeriefirelaunch1.wav
sound/warcraft3/soundpack/frostarmortarget1.wav
sound/warcraft3/soundpack/innerfirebirth.wav
sound/warcraft3/soundpack/reincarnation.wav
sound/warcraft3/soundpack/shadowstrikebirth1.wav
sound/warcraft3/antend.wav
sound/warcraft3/banishcaster.wav
sound/warcraft3/blinkarrival.wav
sound/warcraft3/carrionswarmdamage1.wav
sound/warcraft3/carrionswarmlaunch1.wav
sound/warcraft3/DispelMagicTarget.wav
sound/warcraft3/divineshield.wav
sound/warcraft3/entanglingrootstarget1.wav
sound/warcraft3/error.wav
sound/warcraft3/flamestriketargetwavenonloop1.wav
sound/warcraft3/ImmolationDecay1.wav
sound/warcraft3/impalehit.wav
sound/warcraft3/impalelaunch1.wav
sound/warcraft3/levelupcaster.wav
sound/warcraft3/lightningbolt.wav
sound/warcraft3/locustswarmloop.wav
sound/warcraft3/massteleporttarget.wav
sound/warcraft3/MiniSpiritPissed1.wav
sound/warcraft3/pickupitem.wav
sound/warcraft3/PolymorphDone.wav
sound/warcraft3/PossessionMissileHit1.wav
sound/warcraft3/PossessionMissileLaunch1.wav
sound/warcraft3/PurgeTarget1.wav
sound/warcraft3/resurrecttarget.wav
sound/warcraft3/shadowstrikebirth.wav
sound/warcraft3/shadowstrikemissile1.wav
sound/warcraft3/SpellShieldImpact1.wav
sound/warcraft3/Tomes.wav
sprites/warcraft3/items/wc3_ankh_01.spr
sprites/warcraft3/items/wc3_boot_01.spr
sprites/warcraft3/items/wc3_cat_01.spr
sprites/warcraft3/items/wc3_chameleon_01.spr
sprites/warcraft3/items/wc3_claws_01.spr
sprites/warcraft3/items/wc3_cloak_01.spr
sprites/warcraft3/items/wc3_feather_01.spr
sprites/warcraft3/items/wc3_frost_01.spr
sprites/warcraft3/items/wc3_health_01.spr
sprites/warcraft3/items/wc3_helm_01.spr
sprites/warcraft3/items/wc3_immunity_01.spr
sprites/warcraft3/items/wc3_inferno_01.spr
sprites/warcraft3/items/wc3_mask_01.spr
sprites/warcraft3/items/wc3_mole_01.spr
sprites/warcraft3/items/wc3_protectant_01.spr
sprites/warcraft3/items/wc3_regen_01.spr
sprites/warcraft3/items/wc3_respawn_01.spr
sprites/warcraft3/items/wc3_tome_01.spr
sprites/warcraft3/level/a_level_0.spr
sprites/warcraft3/level/a_level_1.spr
sprites/warcraft3/level/a_level_2.spr
sprites/warcraft3/level/a_level_3.spr
sprites/warcraft3/level/a_level_4.spr
sprites/warcraft3/level/a_level_5.spr
sprites/warcraft3/level/a_level_6.spr
sprites/warcraft3/level/a_level_7.spr
sprites/warcraft3/level/a_level_8.spr
sprites/warcraft3/level/a_level_9.spr
sprites/warcraft3/level/a_level_10.spr
sprites/warcraft3/races/wc3_bloodmage_01.spr
sprites/warcraft3/races/wc3_bloodmage_hi.spr
sprites/warcraft3/races/wc3_chameleon_01.spr
sprites/warcraft3/races/wc3_cryptlord_01.spr
sprites/warcraft3/races/wc3_cryptlord_hi.spr
sprites/warcraft3/races/wc3_elves_01.spr
sprites/warcraft3/races/wc3_elves_hi.spr
sprites/warcraft3/races/wc3_human_01.spr
sprites/warcraft3/races/wc3_human_hi.spr
sprites/warcraft3/races/wc3_none_01.spr
sprites/warcraft3/races/wc3_none_hi.spr
sprites/warcraft3/races/wc3_orc_01.spr
sprites/warcraft3/races/wc3_orc_hi.spr
sprites/warcraft3/races/wc3_shadow_01.spr
sprites/warcraft3/races/wc3_shadow_hi.spr
sprites/warcraft3/races/wc3_undead_01.spr
sprites/warcraft3/races/wc3_undead_hi.spr
sprites/warcraft3/races/wc3_warden_01.spr
sprites/warcraft3/races/wc3_warden_hi.spr
sprites/warcraft3/fireball.spr
sprites/warcraft3/snow.spr
wc3.css

// Map Files
de_nust2.wad
gfx/detail/de_nust2/tarp01.tga
gfx/detail/de_nust2/wood_1.tga
gfx/detail/de_nust2/grd_a1.tga
gfx/detail/de_nust2/wall_.tga
gfx/detail/de_nust2/flr_c1.tga
gfx/detail/de_nust2/gate.tga
gfx/detail/de_nust2/plaster.tga
gfx/detail/de_nust2/wall_c1.tga
gfx/detail/de_nust2/grass.tga
gfx/detail/de_nust2/flr_c2.tga
gfx/detail/de_nust2/wall_06.tga
gfx/detail/de_nust2/wall_b1.tga
gfx/detail/de_nust2/wall_w.tga
gfx/detail/de_nust2/wall_m2.tga
gfx/detail/de_nust2/grd_a2.tga
gfx/env/embassydn.tga
gfx/env/embassybk.tga
gfx/env/embassyrt.tga
gfx/env/embassyup.tga
gfx/env/embassyft.tga
gfx/env/embassylf.tga
maps/de_nust2.res
maps/de_nust2.bsp
maps/de_nust2_detail.txt
maps/de_nust2.txt
models/de_nust2/light.mdl
models/de_nust2/light2.mdl
models/de_nust2/wires.mdl
models/de_nust2/tree2.mdl
models/de_nust2/vertigo_skybox.mdl
models/de_nust2/PC.mdl
models/de_nust2/cabinet1.mdl
models/de_nust2/window.mdl
models/de_nust2/gate.mdl
models/de_nust2/generator3.mdl
models/de_nust2/building2.mdl
models/de_nust2/fence.mdl
models/de_nust2/kia_wheatley.mdl
models/de_nust2/barricade1.mdl
models/de_nust2/table.mdl
models/de_nust2/fence_up.mdl
models/de_nust2/garbage.mdl
models/de_nust2/fan2.mdl
models/de_nust2/chair.mdl
models/de_nust2/worklight.mdl
models/de_nust2/fan.mdl
models/de_nust2/electricbox2.mdl
models/de_nust2/truck1.mdl
models/de_nust2/fading309.mdl
sound/ambience/de_nust2/engine.wav
sound/ambience/de_nust2/hum.wav
sound/ambience/de_nust2/woodlandz.wav
sound/ambience/de_nust2/industrial.wav
sound/ambience/de_nust2/voltage.wav
sound/ambience/de_nust2/air.wav
sound/ambience/de_nust2/aircond.wav
sound/ambience/de_nust2/city.wav
sound/ambience/de_nust2/ambulance.wav
sprites/de_nust2/flare.spr
sprites/de_nust2/glow.spr
sprites/de_nust2/light.spr
